addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

# new options suggested by Alexandre Fayolle
# sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: ogsbu8KfbBq7lsZ5EhWeyJHe0smSimB92DXzWvSpp9CAiyjeha9jKLwWWS/bOjFB2GQSbJjfGl80JD6bB+bqZXzLAh+dn90In7hR/bPY3mg0NrvM6XgF3pY+yX6SRTuag2u3hwrkFpfO39DcsWqgOEamCWf7JzL3spTCeFxrQsdyOhfkq7ZmAMtZ0eCKUZ8537IFoJ6BeckBjmspeF/g23zijNQGCjpD3Mi65DYuGolpbAXIW2ML4jT2qipz/jPdyS+cy9gNxE5iKYr7jD1rSubr7RWhCDPO80iHRfyHjKDLHD3pRADOI4OODbZtiLCg1O1ijj2v6yfENe+a1I0gCYBO5usZGjyL+AWeEirRuWK0Ccsa8pEWliZw9Q/BoGjiMqxAmTzNc1ohu9UVtI04LsJMDYBgIlyyxuwjvES0xfRgi5ftoEVOOkvn6Vgdldx92JXXWlxKYIYG6ZWG/INiklbNuAwDbIsaRBYpYNHTumiauwuphxDvjaSiNi6QIgKaFjBnYytRw4cO5bs90Mwm/mHAnBlNdSFSMwgjkvp2xiQXnQDruIgS1eqMvxPvCoYLX1EVVdhKBoVFGHoI3TI2/XNe6SWLoDBLx1tZOJ/CXyoXtS+lYzS9URnHIc8cogn6JNklwBZYiakbOj2FwJdF3D1QyV7rVDgp3GaHJ+QLrcg=

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  # we install libcups2-dev here because it is not on travis whitelist so it is not installable by addons/apt/packages
  # you can check if available on https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcups2-dev
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git -b 8.0 ${HOME}/odoo-addons

  # odoo argentina
  # TODO change to 8.0 when ready
  - git clone https://github.com/ingadhoc/odoo-argentina.git -b 8.0 ${HOME}/odoo-argentina
  - pip install geopy==0.95.1 BeautifulSoup 

  # oca server tools
  - git clone https://github.com/OCA/server-tools.git ${HOME}/server-tools

  # for odoo pdf reports (tested on sale for eg.)
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
